//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTestApp.WcfService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WcfTestApp.WcfService.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestMailWcfApp@mail.ru.
        /// </summary>
        internal static string EmailSenderLogin {
            get {
                return ResourceManager.GetString("EmailSenderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION.
        /// </summary>
        internal static string EmailSenderMailTheme {
            get {
                return ResourceManager.GetString("EmailSenderMailTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestDevelop123.
        /// </summary>
        internal static string EmailSenderPass {
            get {
                return ResourceManager.GetString("EmailSenderPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.mail.ru.
        /// </summary>
        internal static string EmailSenderServer {
            get {
                return ResourceManager.GetString("EmailSenderServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\smsLoger.txt.
        /// </summary>
        internal static string SmsLogerPath {
            get {
                return ResourceManager.GetString("SmsLogerPath", resourceCulture);
            }
        }
    }
}
